---
-
  canonical: 'автономный округ'
  aliases: [АО]
  dot: false
-
  canonical: 'автономная область'
  aliases: [Аобл]
  dot: false
-
  canonical: город
  aliases: [г]
-
  canonical: край
  aliases: [край]
  dot: false
-
  canonical: область
  aliases: [обл]
-
  canonical: округ
  aliases: [округ]
  dot: false
-
  canonical: республика
  aliases: [Респ]
-
  canonical: чувашия
  aliases: Чувашия
  dot: false
-
  canonical: поселение
  aliases: [п]
-
  canonical: район
  aliases: [р-н]
-
  canonical: территория
  aliases: [тер, терр]
-
  canonical: улус
  aliases: [у]
-
  canonical: волость
  aliases: [волость]
  dot: false
-
  canonical: дачный поселок
  aliases: [дп]
-
  canonical: курортный поселок
  aliases: [кп]
-
  canonical: массив
  aliases: [массив]
  dot: false
-
  canonical: поселок
  aliases: [п пос посёлок]
-
  canonical: почтовое отделение
  aliases: [п/о]
-
  canonical: поселок городского типа
  aliases: [пгт]
-
  canonical: рабочий поселок
  aliases: [рп]
-
  canonical: сельская администрация
  aliases: [с/а]
-
  canonical: сельское муниципальное образо
  aliases: [с/мо]
-
  canonical: сельский округ
  aliases: [с/о]
-
  canonical: сельское поселение
  aliases: [с/п]
-
  canonical: сельсовет
  aliases: [с/с]
-
  canonical: аал
  aliases: [аал]
  dot: false
-
  canonical: автодорога
  aliases: [автодорога]
  dot: false
-
  canonical: арбан
  aliases: [арбан]
  dot: false
-
  canonical: аул
  aliases: [аул]
  dot: false
-
  canonical: выселки(ок)
  aliases: [высел]
-
  canonical: городок
  aliases: [городок]
  dot: false
-
  canonical: деревня
  aliases: [д]
-
  canonical: железнодорожная будка
  aliases: [ж/д_будка]
-
  canonical: железнодорожная казарма
  aliases: [ж/д_казарм]
-
  canonical: ж/д останов. (обгонный) пункт
  aliases: [ж/д_оп]
-
  canonical: железнодорожная платформа
  aliases: [ж/д_платф]
-
  canonical: железнодорожный пост
  aliases: [ж/д_пост]
-
  canonical: железнодорожный разъезд
  aliases: [ж/д_рзд]
-
  canonical: железнодорожная станция
  aliases: [ж/д_ст, ж/д ст]
-
  canonical: жилая зона
  aliases: [жилзона]
-
  canonical: жилой район
  aliases: [жилрайон]
-
  canonical: заимка
  aliases: [заимка]
  dot: false
-
  canonical: казарма
  aliases: [казарма]
  dot: false
-
  canonical: квартал
  aliases: [кв-л, кварт]
-
  canonical: кордон
  aliases: [кордон]
  dot: false
-
  canonical: леспромхоз
  aliases: [лпх]
-
  canonical: местечко
  aliases: [м]
-
  canonical: микрорайон
  aliases: [мкр, мкрн, микр]
-
  canonical: населенный пункт
  aliases: [нп]
-
  canonical: остров
  aliases: [остров]
  dot: false
-
  canonical: планировочный район
  aliases: [п/р]
-
  canonical: поселок и(при) станция(и)
  aliases: [п/ст]
-
  canonical: погост
  aliases: [погост]
  dot: false
-
  canonical: починок
  aliases: [починок]
  dot: false
-
  canonical: промышленная зона
  aliases: [промзона]
-
  canonical: разъезд
  aliases: [рзд]
-
  canonical: село
  aliases: [с]
-
  canonical: слобода
  aliases: [сл]
-
  canonical: садовое неком-е товарищество
  aliases: [снт, садоводство]
-
  canonical: станция
  aliases: [ст-я]
-
  canonical: станица
  aliases: [ст-ца, стн, ст]
-
  canonical: хутор
  aliases: [х]
-
  canonical: абонентский ящик
  aliases: [а/я]
-
  canonical: аллея
  aliases: [аллея]
-
  canonical: берег
  aliases: [берег]
  dot: false
-
  canonical: бульвар
  aliases: [б-р, бул, бульв]
-
  canonical: бугор
  aliases: [бугор]
  dot: false
-
  canonical: вал
  aliases: [вал]
  dot: false
-
  canonical: въезд
  aliases: [въезд]
-
  canonical: гаражно-строительный кооперат
  aliases: [гск]
-
  canonical: дорога
  aliases: [дор]
-
  canonical: животноводческая точка
  aliases: [жт]
-
  canonical: заезд
  aliases: [заезд]
  dot: false
-
  canonical: зона
  aliases: [зона]
  dot: false
-
  canonical: канал
  aliases: [канал, кан]
  dot: false
-
  canonical: километр
  aliases: [км]
-
  canonical: кольцо
  aliases: [кольцо]
  dot: false
-
  canonical: коса
  aliases: [коса]
  dot: false
-
  canonical: линия
  aliases: [линия, лин]
  dot: false
-
  canonical: мост
  aliases: [мост]
  dot: false
-
  canonical: набережная
  aliases: [наб]
-
  canonical: парк
  aliases: [парк]
  dot: false
-
  canonical: переулок
  aliases: [пер, пер-к]
-
  canonical: переезд
  aliases: [переезд]
  dot: false
-
  canonical: площадь
  aliases: [пл]
-
  canonical: платформа
  aliases: [платф]
-
  canonical: площадка
  aliases: [пл-ка]
-
  canonical: полустанок
  aliases: [полустанок]
  dot: false
-
  canonical: проспект
  aliases: [пр-кт, пр, просп, пр-т]
-
  canonical: проезд
  aliases: [проезд, пр-д, прз, прд]
  dot: false
-
  canonical: просек
  aliases: [просек]
  dot: false
-
  canonical: просека
  aliases: [просека]
  dot: false
-
  canonical: проселок
  aliases: [проселок]
  dot: false
-
  canonical: проток
  aliases: [проток]
  dot: false
-
  canonical: протока
  aliases: [протока]
  dot: false
-
  canonical: проулок
  aliases: [проулок]
  dot: false
-
  canonical: ряды
  aliases: [ряды]
  dot: false
-
  canonical: сад
  aliases: [сад]
-
  canonical: сквер
  aliases: [сквер]
  dot: false
-
  canonical: спуск
  aliases: [спуск]
  dot: false
-
  canonical: строение
  aliases: [стр]
-
  canonical: тоннель
  aliases: [тоннель]
-
  canonical: тракт
  aliases: [тр]
-
  canonical: тупик
  aliases: [туп]
-
  canonical: улица
  aliases: [ул]
-
  canonical: участок
  aliases: [уч-к]
-
  canonical: ферма
  aliases: [ферма]
  dot: false
-
  canonical: шоссе
  aliases: [ш, шос]
-
  canonical: эстакада
  aliases: [эстакада]
  dot: false
-
  canonical: гаражно-строительный кооператив
  aliases: [гск]
-
  canonical: дачное некоммерческое партнерство
  aliases: [днп]
-
  canonical: некоммерческое партнерство
  aliases: [н/п]
-
  canonical: садовое товарищество
  aliases: [снт]
-
  canonical: фермерское хозяйство
  aliases: [ф/х]
-
  canonical: коттеджный поселок
  aliases: [кп, коттеджный]
