---
- ['б.', 'большая', 'большой', 'большие', 'большое', 'бол.']
- ['м.', 'малая', 'малый', 'малые', 'малое', 'мал.', 'маршала']
- ['нижн.', 'нижняя', 'нижний', 'нижние', 'нижнее', 'ниж.']
- ['верхн.', 'верхняя', 'верхний', 'верхние', 'верхнее', 'верх.']
- ['ср.', 'средний', 'средняя', 'средние', 'среднее']
- ['стар.', 'старый', 'старая', 'старые', 'старое']
- ['новая', 'нов.', 'н.', 'новый', 'новое']
- ['северное', 'северная', 'северный']
- ['южное', 'южная', 'южный']
- ['восточное', 'восточная', 'восточный']
- ['западное', 'западная', 'западный']
- ['соцтруда', 'соц.труда', '']
- ['им', 'имени', 'им.', '']
- ['ак.', 'академика', '']
- ['героя советского союза', '']
- ['героя ссср', '']
- ['героя', '']
- ['писателя', '']
- ['генерала', '']
- ['адмирала', '']
- ['генерал-лейтенанта', '']
- ['поэта-декабриста', '']
- ['композитора', '']
- ['братьев', 'бр.', '']
- ['архитектора', '']
- ['генерала армии', '']
- ['космонавта', '']
- ['милиционера', '']
- ['авиаконструктора', '']
- ['маршала', '']
- ['авиаконструктора', '']
- ['матроса', '']
- ['профессора', '']
- ['тиз', '']
- ['реки', '']
- ['солдата', '']
- ['цюрупа', 'цурюпа', 'цурюпы', 'цюрупы']
- ['в.о.', 'васильевского', 'васильевского острова', 'во', '']
- ['п.с.', 'петроградки', 'петроградской стороны', 'пс', '']
- ['пограничника', '']
- ['линия', '']
- ['вал', '']
- ['канала', 'кан.', '']
- ['комиссара', '']
- ['лат.', 'латышских']
- ['танкиста', '']
- ['подводника', 'подв.', '']
- ['совхоз', 'свх']
- ['политрука', '']